name: Sync Echo Submodule

on:
  push:
    branches:
      - master # or main, depending on your default branch

jobs:
  sync-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.SUBMODULES_PAT }} # Use SUBMODULES_PAT for pushing to submodules

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check for changes in Echo submodule
        id: check_echo_changes
        run: |
          cd Echo
          git status --porcelain > changes.txt
          if [ -s changes.txt ]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi
        
      - name: Commit and push changes in Echo submodule
        if: steps.check_echo_changes.outputs.has_changes == 'true'
        run: |
          cd Echo
          git add .
          git commit -m "Automated: Sync changes from main repo workflow"
          # Push to Echo's remote. Replace with actual URL if different.
          # This assumes Echo has its own remote.
          # You might need a PAT with repo scope for this if GITHUB_TOKEN is insufficient.
          # Push to Echo's remote using the PAT. Replace 'github.com/your-username/Echo.git' with the actual remote URL of your Echo submodule.
          git push https://oauth2:${{ secrets.SUBMODULES_PAT }}@github.com/john-ogletree/Echo.git master # or main, depending on Echo's default branch

      - name: Update main repository submodule reference
        if: steps.check_echo_changes.outputs.has_changes == 'true'
        run: |
          git add Echo
          git commit -m "Automated: Update Echo submodule reference"
          git push origin master # or main, depending on your default branch
